spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.246.208:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mw970420


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.xwgames.blog: info
  file: log/blog-pro.log

server:
  port: 8081